# Curator configuration
# https://www.elastic.co/docs/reference/elasticsearch/curator/configfile

elasticsearch:
  client:
    hosts: [ http://elasticsearch:9200 ]
  other_settings:
    username: elastic
    password: ${ELASTIC_PASSWORD}

logging:
  loglevel: INFO
  logformat: default
